import { createHash } from 'node:crypto'
import { z } from 'zod'

export const qcSeverityValues = ['info', 'warning', 'critical'] as const
export type QcSeverity = (typeof qcSeverityValues)[number]

export const qcStepValues = [
  'initial_visit',
  'pain_evaluation',
  'procedure',
  'discharge',
  'case_summary',
  'cross_step',
] as const
export type QcStep = (typeof qcStepValues)[number]

export const qcOverallAssessmentValues = [
  'clean',
  'minor_issues',
  'major_issues',
  'incomplete',
] as const
export type QcOverallAssessment = (typeof qcOverallAssessmentValues)[number]

// Single finding from AI tool output
export const qualityFindingSchema = z.object({
  severity: z.enum(qcSeverityValues),
  step: z.enum(qcStepValues),
  note_id: z.string().uuid().nullable(),
  procedure_id: z.string().uuid().nullable(),
  section_key: z.string().nullable(),
  message: z.string().min(1),
  rationale: z.string().nullable(),
  suggested_tone_hint: z.string().nullable(),
})
export type QualityFinding = z.infer<typeof qualityFindingSchema>

// Full AI tool output schema
export const qualityReviewResultSchema = z.object({
  findings: z.array(qualityFindingSchema),
  summary: z.string().nullable(),
  overall_assessment: z.enum(qcOverallAssessmentValues),
})
export type QualityReviewResult = z.infer<typeof qualityReviewResultSchema>

// Provider-override layer
export const findingOverrideStatusValues = [
  'acknowledged',
  'dismissed',
  'edited',
  'resolved',
  'fix_in_progress',
] as const
export type FindingOverrideStatus = (typeof findingOverrideStatusValues)[number]

export const findingResolutionSourceValues = [
  'auto_recheck',
  'manual_verify',
  'manual_resolve',
] as const
export type FindingResolutionSource = (typeof findingResolutionSourceValues)[number]

export const findingOverrideEntrySchema = z.object({
  status: z.enum(findingOverrideStatusValues),
  dismissed_reason: z.string().nullable(),
  edited_message: z.string().nullable(),
  edited_rationale: z.string().nullable(),
  edited_suggested_tone_hint: z.string().nullable(),
  actor_user_id: z.string().uuid(),
  set_at: z.string(),
  // Resolution metadata. Both null when status != 'resolved'. resolved_at
  // captures the moment the entry flipped to resolved (auto via Recheck or
  // manual via Verify / Mark Resolved). resolution_source distinguishes the
  // three resolution paths so UI can label appropriately. Existing rows
  // persisted before this change parse fine because both fields default to
  // null when absent from the JSON payload.
  resolved_at: z.string().nullable().default(null),
  resolution_source: z.enum(findingResolutionSourceValues).nullable().default(null),
  // Fix-action audit fields. fix_attempted_at: timestamp of last Fix click.
  // fix_section_regenerated: which section column was regenerated by the Fix.
  // fix_recheck_result: whether the targeted finding hash survived the
  // post-fix recheck. All nullable so existing rows persisted before this
  // change parse fine.
  fix_attempted_at: z.string().nullable().default(null),
  fix_section_regenerated: z.string().nullable().default(null),
  fix_recheck_result: z.enum(['resolved', 'still_present']).nullable().default(null),
})
export type FindingOverrideEntry = z.infer<typeof findingOverrideEntrySchema>

export const findingOverridesMapSchema = z.record(z.string(), findingOverrideEntrySchema)
export type FindingOverridesMap = z.infer<typeof findingOverridesMapSchema>

export const findingEditFormSchema = z.object({
  edited_message: z.string().min(1, 'Required'),
  edited_rationale: z.string().nullable(),
  edited_suggested_tone_hint: z.string().nullable(),
})
export type FindingEditFormValues = z.infer<typeof findingEditFormSchema>

export const findingDismissFormSchema = z.object({
  dismissed_reason: z.string().nullable(),
})
export type FindingDismissFormValues = z.infer<typeof findingDismissFormSchema>

// Stable hash for a finding — used as the key into FindingOverridesMap.
// Inputs are exactly the fields a regen would re-emit identically when the
// underlying drift has not changed; messages reordered or slightly reworded
// will hash differently, which is acceptable: the override layer is wiped
// on regen anyway.
export function computeFindingHash(finding: QualityFinding): string {
  const parts = [
    finding.severity,
    finding.step,
    finding.note_id ?? '',
    finding.procedure_id ?? '',
    finding.section_key ?? '',
    finding.message,
  ].join('|')
  return createHash('sha256').update(parts).digest('hex')
}

// Steps for which Fix action is supported. cross_step + case_summary findings
// have no single regenerable target, so Fix is not offered.
const FIXABLE_STEPS = new Set<QcStep>([
  'initial_visit',
  'pain_evaluation',
  'procedure',
  'discharge',
])

// Synthetic section_key sentinels used by deterministic validators. These do
// not map to real note section columns, so Fix cannot route them to a section
// regenerator. Provider uses Verify (deterministic re-run) instead.
const SYNTHETIC_SECTION_KEYS = new Set<string>([
  '_qc_external_cause_chain',
  '_qc_seventh_character_integrity',
])

export type FindingFixEligibility =
  | { fixable: true }
  | { fixable: false; reason: string }

// Pure predicate shared by server action gate and UI button gate. Returns the
// reason when ineligible so the UI can surface it as a tooltip.
export function findingFixEligibility(finding: QualityFinding): FindingFixEligibility {
  if (!FIXABLE_STEPS.has(finding.step)) {
    return {
      fixable: false,
      reason: 'Cross-step and case-summary findings are not auto-fixable',
    }
  }
  if (!finding.section_key) {
    return { fixable: false, reason: 'Finding has no target section' }
  }
  if (SYNTHETIC_SECTION_KEYS.has(finding.section_key)) {
    return {
      fixable: false,
      reason: 'Deterministic findings are not auto-fixable; use Verify',
    }
  }
  if (finding.step === 'procedure' && !finding.procedure_id) {
    return { fixable: false, reason: 'Procedure finding missing procedure_id' }
  }
  if (finding.step !== 'procedure' && !finding.note_id) {
    return { fixable: false, reason: 'Finding missing note_id' }
  }
  return { fixable: true }
}
