'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { getCurrentUserWithRole } from '@/lib/auth/require-role'
import {
  createPatientCaseInputSchema,
  type CreatePatientCaseInput,
  editPatientSchema,
  type EditPatientValues,
  editCaseSchema,
  type EditCaseValues,
} from '@/lib/validations/patient'

export async function checkDuplicatePatient(
  firstName: string,
  lastName: string,
  dob: string
) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('patients')
    .select('id, first_name, last_name, date_of_birth')
    .ilike('first_name', firstName)
    .ilike('last_name', lastName)
    .eq('date_of_birth', dob)
    .is('deleted_at', null)

  if (error) {
    return { error: error.message, duplicates: [] }
  }

  return { duplicates: data ?? [] }
}

export async function createPatientCase(data: CreatePatientCaseInput) {
  const parsed = createPatientCaseInputSchema.safeParse(data)
  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors }
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  // Admin-only: allow creating a case at a non-intake status
  const me = await getCurrentUserWithRole()
  const requestedStatus = parsed.data.case_status ?? 'intake'
  if (requestedStatus !== 'intake' && me?.role !== 'admin') {
    return { error: 'Only an administrator can create a case at a non-intake status.' }
  }

  let patientId: string

  if (parsed.data.mode === 'existing_patient') {
    const { data: existing, error: lookupError } = await supabase
      .from('patients')
      .select('id')
      .eq('id', parsed.data.patient_id)
      .is('deleted_at', null)
      .maybeSingle()

    if (lookupError) return { error: lookupError.message }
    if (!existing) return { error: 'Patient not found' }

    patientId = existing.id
  } else {
    const {
      first_name, last_name, middle_name, date_of_birth, gender,
      phone_primary, email, address_line1, address_line2, city, state, zip_code,
    } = parsed.data

    const { data: patient, error: patientError } = await supabase
      .from('patients')
      .insert({
        first_name,
        last_name,
        middle_name: middle_name || null,
        date_of_birth,
        gender: gender || null,
        phone_primary: phone_primary || null,
        email: email || null,
        address_line1: address_line1 || null,
        address_line2: address_line2 || null,
        city: city || null,
        state: state || null,
        zip_code: zip_code || null,
        created_by_user_id: user?.id,
        updated_by_user_id: user?.id,
      })
      .select()
      .single()

    if (patientError) return { error: patientError.message }
    patientId = patient.id
  }

  const {
    accident_date, accident_type, accident_description,
    attorney_id, assigned_provider_id, lien_on_file,
  } = parsed.data

  // Insert case (case_number auto-generated by trigger)
  const { data: caseRecord, error: caseError } = await supabase
    .from('cases')
    .insert({
      patient_id: patientId,
      attorney_id,
      assigned_provider_id,
      accident_date: accident_date || null,
      accident_type: accident_type || null,
      accident_description: accident_description || null,
      lien_on_file: lien_on_file ?? false,
      case_status: requestedStatus,
      case_close_date:
        requestedStatus === 'closed' || requestedStatus === 'archived'
          ? new Date().toISOString().split('T')[0]
          : null,
      created_by_user_id: user?.id,
      updated_by_user_id: user?.id,
    })
    .select()
    .single()

  if (caseError) {
    return { error: caseError.message }
  }

  // Insert initial status history
  await supabase.from('case_status_history').insert({
    case_id: caseRecord.id,
    new_status: requestedStatus,
    changed_by_user_id: user?.id,
  })

  revalidatePath('/patients')
  return { data: caseRecord }
}

export async function getPatientForNewCase(patientId: string) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('patients')
    .select('id, first_name, last_name, middle_name, date_of_birth, gender')
    .eq('id', patientId)
    .is('deleted_at', null)
    .maybeSingle()

  if (error) return { error: error.message }
  if (!data) return { error: 'Patient not found' }

  return { data }
}

export async function getPatientCase(caseId: string) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('cases')
    .select(`
      *,
      patient:patients(*),
      attorney:attorneys(*)
    `)
    .eq('id', caseId)
    .is('deleted_at', null)
    .single()

  if (error) {
    return { error: error.message }
  }

  return { data }
}

export async function listPatients() {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('patients')
    .select(`
      id,
      first_name,
      last_name,
      date_of_birth,
      phone_primary,
      cases(id, case_status, accident_date, balance_due, updated_at)
    `)
    .is('deleted_at', null)
    .order('last_name', { ascending: true })

  if (error) {
    return { error: error.message, data: [] }
  }

  const normalized = (data ?? []).map((row) => {
    const cases = (Array.isArray(row.cases) ? row.cases : []).filter(
      (c) => c.case_status !== 'archived'
    )
    const activeCount = cases.filter((c) =>
      ['intake', 'active', 'pending_settlement'].includes(c.case_status)
    ).length
    const pendingImagingCount = cases.filter((c) => c.case_status === 'pending_imaging').length
    const balanceTotal = cases.reduce((sum, c) => sum + Number(c.balance_due ?? 0), 0)
    const lastActivity = cases
      .map((c) => c.updated_at)
      .filter(Boolean)
      .sort()
      .pop() ?? null
    const lastAccident = cases
      .map((c) => c.accident_date)
      .filter(Boolean)
      .sort()
      .pop() ?? null
    return {
      id: row.id,
      first_name: row.first_name,
      last_name: row.last_name,
      date_of_birth: row.date_of_birth,
      phone_primary: row.phone_primary,
      case_count: cases.length,
      active_case_count: activeCount,
      pending_imaging_case_count: pendingImagingCount,
      balance_total: balanceTotal,
      last_activity: lastActivity,
      last_accident_date: lastAccident,
    }
  })

  return { data: normalized }
}

export async function getPatientWithCases(patientId: string) {
  const supabase = await createClient()

  const { data: patient, error: patientError } = await supabase
    .from('patients')
    .select('*')
    .eq('id', patientId)
    .is('deleted_at', null)
    .maybeSingle()

  if (patientError) return { error: patientError.message }
  if (!patient) return { error: 'Patient not found' }

  const { data: cases, error: casesError } = await supabase
    .from('cases')
    .select('id, case_number, case_status, accident_date, accident_type, total_billed, total_paid, balance_due, created_at')
    .eq('patient_id', patientId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false })

  if (casesError) return { error: casesError.message }

  return { data: { patient, cases: cases ?? [] } }
}

export async function listPatientCases(search?: string) {
  const supabase = await createClient()

  let query = supabase
    .from('cases')
    .select(`
      id,
      case_number,
      case_status,
      accident_date,
      created_at,
      attorney_id,
      patient:patients(id, first_name, last_name),
      attorney:attorneys(id, first_name, last_name, firm_name),
      discharge_notes(visit_date, deleted_at)
    `)
    .is('deleted_at', null)
    .order('created_at', { ascending: false })

  if (search) {
    query = query.or(
      `case_number.ilike.%${search}%,patient.first_name.ilike.%${search}%,patient.last_name.ilike.%${search}%`
    )
  }

  const { data, error } = await query

  if (error) {
    return { error: error.message, data: [] }
  }

  // Normalize patient from array to single object (Supabase returns array for relations)
  const normalized = (data ?? []).map((row) => {
    // Embedded discharge_notes come back as an array including soft-deleted rows.
    // The unique-active index guarantees at most one non-deleted note per case.
    const activeDischarge = (Array.isArray(row.discharge_notes) ? row.discharge_notes : []).find(
      (d) => d.deleted_at === null
    )
    // eslint-disable-next-line @typescript-eslint/no-unused-vars -- strip raw child array from returned shape
    const { discharge_notes: _discharge_notes, ...rest } = row
    return {
      ...rest,
      patient: Array.isArray(row.patient) ? row.patient[0] ?? null : row.patient,
      attorney: Array.isArray(row.attorney) ? row.attorney[0] ?? null : row.attorney,
      discharge_visit_date: activeDischarge?.visit_date ?? null,
    }
  })

  return { data: normalized }
}

export async function updatePatient(patientId: string, data: EditPatientValues) {
  const parsed = editPatientSchema.safeParse(data)
  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors }
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const { error } = await supabase
    .from('patients')
    .update({
      first_name: parsed.data.first_name,
      last_name: parsed.data.last_name,
      middle_name: parsed.data.middle_name || null,
      date_of_birth: parsed.data.date_of_birth,
      gender: parsed.data.gender || null,
      phone_primary: parsed.data.phone_primary || null,
      email: parsed.data.email || null,
      address_line1: parsed.data.address_line1 || null,
      address_line2: parsed.data.address_line2 || null,
      city: parsed.data.city || null,
      state: parsed.data.state || null,
      zip_code: parsed.data.zip_code || null,
      updated_by_user_id: user.id,
    })
    .eq('id', patientId)
    .is('deleted_at', null)

  if (error) return { error: error.message }

  revalidatePath('/people')
  revalidatePath(`/people/${patientId}`)
  return { data: { success: true } }
}

export async function deletePatient(patientId: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const { count, error: countError } = await supabase
    .from('cases')
    .select('id', { count: 'exact', head: true })
    .eq('patient_id', patientId)
    .is('deleted_at', null)

  if (countError) return { error: countError.message }
  if ((count ?? 0) > 0) {
    return { error: 'Cannot delete patient with attached cases' }
  }

  const { error } = await supabase
    .from('patients')
    .update({
      deleted_at: new Date().toISOString(),
      updated_by_user_id: user.id,
    })
    .eq('id', patientId)
    .is('deleted_at', null)

  if (error) return { error: error.message }

  revalidatePath('/people')
  return { data: { success: true } }
}

export async function updateCase(caseId: string, data: EditCaseValues) {
  const parsed = editCaseSchema.safeParse(data)
  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors }
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const { error } = await supabase
    .from('cases')
    .update({
      accident_date: parsed.data.accident_date || null,
      accident_type: parsed.data.accident_type || null,
      accident_description: parsed.data.accident_description || null,
      attorney_id: parsed.data.attorney_id,
      assigned_provider_id: parsed.data.assigned_provider_id,
      lien_on_file: parsed.data.lien_on_file,
      updated_by_user_id: user.id,
    })
    .eq('id', caseId)
    .is('deleted_at', null)

  if (error) return { error: error.message }

  revalidatePath(`/patients/${caseId}`)
  return { data: { success: true } }
}
